# Generated by Django 4.1.4 on 2022-12-14 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AOT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aot',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aot',
            name='img_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aot',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Titan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('img_url', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
